version: "3.8"

services:
  jenkins:
    build: .
    container_name: jenkins
    hostname: jenkins
    privileged: true
    ports:
      - 4444:8080
      - 50000:50000
    volumes:
      - ../data/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock