FROM ubuntu:22.04

RUN apt update && apt install  openssh-server sudo curl vim git zsh unzip -y

USER root
RUN wget -O /usr/share/keyrings/jenkins-keyring.asc https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
RUN echo deb [trusted=yes] https://pkg.jenkins.io/debian-stable binary/ | sudo tee /etc/apt/sources.list.d/jenkins.list > /dev/null
RUN apt-get update
RUN apt-get upgrade -y
RUN apt install fontconfig openjdk-17-jre -y
RUN apt-get install jenkins -y

CMD [ "cat", "/lib/systemd/system/jenkins.service" ]