import './globals.css'

import Navbar from './components/Navbar'
import MyProfilePic from './components/MyProfilePic'

export const metadata = {
  title: 'XUE Blog',
  description: 'Generated by XUE',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="dark:bg-slate-800">
        <Navbar></Navbar>
        <MyProfilePic></MyProfilePic>
        {children}
      </body>
    </html>
  )
}
