version: "3.8"

services:
  nbp_production:
    image: nbp_production
    build:
      dockerfile: production.Dockerfile
    container_name: nbp_production
    hostname: nbp_production
    ports:
      - 3000:3000