export interface Credential {
  ['API_USER']: string
  ['API_KEY']: string
}

export interface TransaferRequest {
  ['man']?: string
  ['tea']?: string
  ['soc']?: string
  ['ip']?: string
  ['dfp']?: string
  ['dft']?: string
  ['bfn']?: string
  ['bmn']?: string
  ['bln']?: string
  ['bln2']?: string
  ['bgd']?: 'M' | 'F'
  ['bsn']?: string
  ['bco']?: string
  ['bz']?: string
  ['bc']?: string
  ['bs']?: string
  ['bnbh']?: string
  ['sfn']?: string
  ['sln']?: string
  ['ssn']?: string
  ['sco']?: string
  ['sz']?: string
  ['sc']?: string
  ['ss']?: string
  ['shipFromStreet']?: string
  ['shipFromCity']?: string
  ['shipFromState']?: string
  ['shipFromPostalCode']?: string
  ['shipFromCountry']?: string
  ['shipFromCounty']?: string
  ['sellerStreet']?: string
  ['sellerCity']?: string
  ['sellerState']?: string
  ['sellerPostalCode']?: string
  ['sellerCountry']?: string
  ['sellerCounty']?: string
  ['clong']?: string
  ['clat']?: string
  ['blg']?: string
  ['aflid']?: string
  ['aflsd']?: string
  ['phn']?: string
  ['pm']?: string
  ['pw']?: string
  ['tti']?: string
  ['tid']?: string
  ['pccn']?: string
  ['pcct']?: string
  ['pcty']?: string
  ['phash']?: string
  ['ptoken']?: string
  ['pach']?: string
  ['pbc']?: string
  ['profile']?: string
  ['smna']?: string
  ['m']?: string
  ['accountCreationTime']?: number
  ['sdcad']?: string[]
  ['ddcad']?: string[]
  ['dcth']?: string
  ['timezone']?: string
  ['cnbvot']?: string
  ['cnbvmi']?: string
  ['cnbvct']?: string
  ['cnbvrcn']?: string
  ['cnbvea']?: string
  ['cnbvrfcd']?: string
  ['nationality']?: string
  ['agent']?: string
  ['agentpln']?: string
  ['agentmln']?: string
  ['agentcurp']?: string
  ['agentrfc']?: string
  ['tags']?: string[]
  ['mcc']?: string
  ['useRiskMatrix']?: boolean
  ['cnv_rate']?: string
  ['moto']?: string
  ['pppe']?: string
  ['pppi']?: string
  ['ppps']?: string
  ['pppc']?: string
  ['amt']?: string
  ['ccy']?: string
  ['dman']?: string
  ['demail']?: string
  ['dph']?: string
  ['dpccn']?: string
  ['dpcct']?: string
  ['dphash']?: string
  ['dpppe']?: string
  ['dpppi']?: string
  ['dptoken']?: string
  ['dpach']?: string
  ['dpbc']?: string
  ['dassnl4']?: string
  ['ddob']?: string
  ['smid']?: string
  ['additionalParams']?: {
    [key:string]: any
  }
  ['retailer']?: string
  ['assnl4']?: string
  ['assn']?: string
  ['assn1']?: string
  ['assn2']?: string
  ['nationalId']?: string
  ['nationalIdMasked']?: string
  ['taxId']?: string
  ['taxIdMasked']?: string
  ['voterId']?: string
  ['voterIdMasked']?: string
  ['driverId']?: string
  ['driverIdMasked']?: string
  ['passportId']?: string
  ['passportIdMasked']?: string
  ['multiPayment']?: {
    [key:string]: any
  }
  ['getdNationalId']?: string
  ['getdNationalIdMasked']?: string
  ['getdTaxId']?: string
  ['getdTaxIdMasked']?: string
  ['getdVoterId']?: string
  ['getdVoterIdMasked']?: string
  ['getdDriverId']?: string
  ['getdDriverIdMasked']?: string
  ['getdPassportId']?: string
  ['getdPassportIdMasked']?: string
  ['retail_city']?: string
  ['retail_state']?: string
  ['retail_country']?: string
  ['retail_zip']?: string
  ['payment_source']?: string
  ['request_code']?: string
  //Memos
  [key:string]: any
}