service: python-thumbnail

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  stage: dev
  timeout: 10
  memorySize: 128
  environment:
    THUMBNAIL_SIZE: 128
    REGION_NAME: ${self:provider.region}
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Resource: 
            - 'arn:aws:s3:::${self:custom.bucket}/*'
          Action:
            - "s3:*"

custom:
  bucket: xrw-thumbnails
  pythonRequirements:
    dockerizePip: true

functions:
  s3_thumbnail_generator:
    handler: handler.s3_thumbnail_generator
    reservedConcurrency: 4
    events:
      - s3:
          bucket: ${self:custom.bucket}
          event: s3:ObjectCreated:*
          rules:
            - suffix: .png

plugins:
  - serverless-python-requirements
