version: '3'

services:
  mysql:
    container_name: mysql_8
    image: mysql:8.1
    ports:
      - "3306:3306"
    volumes:
      - "$PWD/data/mysql_8:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: '123456'