version: "3.8"

services:
  nbp_browser:
    image: xuerong/nbp-browser
    container_name: nbp_browser
    hostname: nbp_browser
    env_file:
      - ./browser.env
    # environment:
    #   - NODE_ENV=dev
    ports:
      - 80:3000
    networks:
      - nbp-ec2-compose_nbp-ec2-network
  nbp_server:
    build: xuerong/nbp-server
    container_name: nbp_server
    hostname: nbp_server
    env_file:
      - ./server.env
    ports:
      - 3040:3040
    networks:
      - nbp-ec2-compose_nbp-ec2-network

networks:
  nbp-ec2-compose_nbp-ec2-network:
    external: true
