version: "3.8"

services:
  nbp_browser:
    build: ../../browser 
    container_name: nbp_browser
    hostname: nbp_browser
    # env_file:
    #   - ./browser.env
    # environment:
    #   - NODE_ENV=dev
    depends_on:
      - mysql
    ports:
      - 3000:3000
    networks:
      - nbp-ec2-network
  mysql:
    container_name: mysql_8
    image: mysql:8.1
    ports:
      - "3306:3306"
    volumes:
      - ../data/mysql_8:/var/lib/mysql
      - /tmp/:/tmp/
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
    networks:
      - nbp-ec2-compose_nbp-ec2-network
  nbp_server:
    build: ../../server_v2 
    container_name: nbp_server
    hostname: nbp_server
    depends_on:
      - mysql
    env_file:
      - ./server.env
    ports:
      - 3040:3040
    networks:
      - nbp-ec2-compose_nbp-ec2-network

networks:
  nbp-ec2-compose_nbp-ec2-network:
    external: true