import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import NextUIProvider from './providers/NextUIProvider'

import Nav from './components/layout/nav'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'NBP',
  description: 'Generated by XRW',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextUIProvider>
          {/* <main> */}
            <Nav></Nav>
            <div className="max-w-[1024px] px-6 mx-auto">
              {children}
            </div>
          {/* </main> */}
        </NextUIProvider>
      </body>
    </html>
  )
}
